# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FastHTML_MSOAuth',
                'doc_host': 'https://ChuckNoelke.github.io',
                'git_url': 'https://github.com/ChuckNoelke/FastHTML_MSOAuth',
                'lib_path': 'FastHTML_MSOAuth'},
  'syms': {'FastHTML_MSOAuth.core': {'FastHTML_MSOAuth.core.foo': ('core.html#foo', 'FastHTML_MSOAuth/core.py')}}}
